#!/usr/bin/env bash

resolve_app_desc() {
  check_if_func_args_num_at_least 1 "app_name, app_version"
  local app_name=$1
  local app_version=$2
  
  if [ -z "$app_version" ]; then
    echo "$1"
  else
    echo "$1 v$2"
  fi
}

resolve_app_id() {
  check_if_func_args_num_equals_to 2 "app_name, app_version"
  echo "$1-$2"
}

parse_app_id_from_install_file() {
  check_if_func_args_num_equals_to 1 "tar_gz_filepath"

  local tar_gz_filename=$(basename $1)
  local result="${tar_gz_filename%.tar.gz}"
  echo "${result%%_*}"
}
