#!/usr/bin/env bash

install_app_as_systemd_service() {
  check_if_func_args_num_at_least 1 "app_name, systemd_service_name, app_version"
  local app_name=$1
  local systemd_service_name=$2
  local app_version=$3
  
  local install_files_dir=$(get_install_files_dir)
  local install_tar_gz_filename=$(resolve_unique_install_filename $app_name $app_version)
  local install_tar_gz_filepath="${install_files_dir}/${install_tar_gz_filename}"
  
  local tmp_extracted_dirpath="$(get_tmp_extracted_dir $app_name $app_version)"
  tar zxf $install_tar_gz_filepath -C /tmp
  
  show_msg_app_install_may_take_a_while $app_name
  safely_install_local_pkgs_offline $tmp_extracted_dirpath
  rm -rf $tmp_extracted_dirpath
  
  exec_command_quietly "systemctl start ${systemd_service_name}"
  exec_command_quietly "systemctl enable ${systemd_service_name} 2>/dev/null"
}

get_tmp_extracted_dir() {
  check_if_func_args_num_at_least 1 "app_name, app_version"
  local app_name=$1
  local app_version=$2
  
  local result="/tmp/$app_name"
  if [ ! -z "$app_version" ]; then
    result="${result}-${app_version}"
  fi
  
  echo "$result"
}